version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - npm run build --if-present
  post_build:
    commands:
      - npm ci --production
